const planets = {
    sun: {
        image: 'https://photojournal.jpl.nasa.gov/jpegMod/PIA25628_modest.jpg',
        name: 'Sun',
        satellite: 'Sun',
        mision: 'NuSTAR ',
        spacecraft: 'InSAR ',
        url: 'https://photojournal.jpl.nasa.gov/target/Sun',
    },
    mercury: {
        image: 'https://photojournal.jpl.nasa.gov/jpegMod/PIA19497_modest.jpg',
        name: 'Mercury',
        satellite: 'Sun',
        mision: 'MESSENGER ',
        spacecraft: 'MESSENGER ',
        url: 'https://photojournal.jpl.nasa.gov/targetFamily/Mercury',
    },
    venus: {
        image: 'https://photojournal.jpl.nasa.gov/browse/PIA23791.jpg',
        name: 'Venus',
        satellite: 'Sun',
        mision: 'Centinela-1',
        spacecraft: 'InSAR ',
        url: 'https://photojournal.jpl.nasa.gov/targetFamily/Venus',
    },
    earth: {
        image: 'https://ichef.bbci.co.uk/images/ic/1200x675/p0g08wkx.jpg',
        name: 'Earth',
        satellite: 'Sun',
        mision: 'Mariner',
        spacecraft: 'Mariner 10',
        url: 'https://photojournal.jpl.nasa.gov/targetFamily/Earth',
    },
    mars: {
        image: 'https://photojournal.jpl.nasa.gov/jpegMod/PIA26154_modest.jpg',
        name: 'Mars',
        satellite: 'Sun ',
        mision: '2001 Mars Odyssey ',
        spacecraft: '	2001 Mars Odyssey',
        url: 'https://photojournal.jpl.nasa.gov/targetFamily/Mars',
    },
    jupiter: {
        image: 'https://photojournal.jpl.nasa.gov/jpegMod/PIA25726_modest.jpg',
        name: 'Jupiter',
        satellite: 'Sun',
        mision: 'Juno',
        spacecraft: 'Juno',
        url: 'https://photojournal.jpl.nasa.gov/targetFamily/Jupiter',
    },
    saturn: {
        image: 'https://photojournal.jpl.nasa.gov/jpegMod/PIA24027_modest.jpg',
        name: 'Enceladus',
        satellite: 'Saturn',
        mision: 'Cassini-Huygens',
        spacecraft: 'Cassini Orbiter',
        url: 'https://photojournal.jpl.nasa.gov/targetFamily/Saturn',
    },
    uranus: {
        image: 'https://photojournal.jpl.nasa.gov/jpegMod/PIA25951_modest.jpg',
        name: 'Triton',
        satellite: 'Neptune',
        mision: 'Trident ',
        spacecraft: 'Trident ',
        url: 'https://photojournal.jpl.nasa.gov/targetFamily/Uranus',
    },
    neptune: {
        image: 'https://photojournal.jpl.nasa.gov/jpegMod/PIA23874_modest.jpg',
        name: 'Triton',
        satellite: 'Neptune',
        mision: 'Trident',
        spacecraft: 'Nothing',
        url: 'https://photojournal.jpl.nasa.gov/targetFamily/Neptune',
    },
};
